In [1]:
from datetime import datetime, timedelta
import pandas as pd
import numpy as np
import json

In [7]:
datetime(1,1,1)

datetime.datetime(1, 1, 1, 0, 0)

In [2]:
pd.datetime.now()

/home/danil/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime instead.
  """Entry point for launching an IPython kernel.


datetime.datetime(2020, 9, 18, 22, 41, 14, 479909)

In [17]:
datetime.now()

datetime.datetime(2020, 9, 18, 17, 2, 12, 835746)

In [21]:
datetime.now() - timedelta(days=1)

datetime.datetime(2020, 9, 17, 17, 2, 42, 972858)

In [7]:
import dash_daq as daq

In [2]:
df1 = pd.read_excel('./ActualDataFeb2020.xlsx')

In [19]:
df1.iloc[:,1]

0      309.94
1      315.52
2      308.43
3      320.57
4      320.70
        ...  
843    328.01
844    328.26
845    334.60
846    329.48
847    330.67
Name: Gpp, Length: 848, dtype: float64

In [17]:
min((10,df1.shape[1]))

10

In [21]:
for v, i in enumerate(df1.iloc[:,1]):
    print(i)

309.94
315.52
308.43
320.57
320.7
319.28
322.76
316.44
322.76
320.68
318.76
303.63
304.31
305.62
307.21
303.37
302.73
315.66
316.95
316.79
317.31
317.43
315.35
316.8
316.16
316.16
315.91
317.07
315.51
316.42
317.98
318.51
318.51
316.82
318.5
315.79
315.4
314.89
317.48
315.3
314.91
321.92
320.12
320.64
318.2
317.81
319.21
319.86
317.16
316.25
316.76
319.08
320.25
319.99
320.12
319.73
317.64
319.05
317.36
317.88
320.84
318.01
318.27
317.88
315.69
318.02
319.56
315.3
316.59
316.96
314.12
312.45
319.16
315.91
317.06
317.87
317.25
318.41
320.73
315.54
321.08
321.33
316.18
318.5
316.71
319.38
322.3
317.74
317.22
320.44
319.8
321.22
318.64
319.63
322.15
320.06
322.75
322.76
317.88
320.34
320.35
320.35
321.1
324.06
321.33
324.28
323.89
322.33
320.14
322.74
322.75
322.86
324.68
323.68
323.71
320.76
322.05
319.98
322.85
322.6
325.18
323.49
323.48
325.68
324.53
322.75
319.64
322.87
326.25
325.86
323.96
322.74
318.5
319.92
321.87
315.96
319.0
320.57
319.3
314.78
318.17
321.3
316.28
315.48
314.02
3

In [1]:
[1]+[2]

[1, 2]

In [23]:
df = pd.read_csv('AutoDataset.csv')

In [24]:
df.columns=[x[1:] for x in df.columns]

In [25]:
df.head()

symboling  normalized-losses         make fuel-type aspiration  \
0          3                NaN  alfa-romero       gas        std   
1          3                NaN  alfa-romero       gas        std   
2          1                NaN  alfa-romero       gas        std   
3          2              164.0         audi       gas        std   
4          2              164.0         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0      111.0   
1          130         mpfi  3.47    2.68               9.0      111.0   
2          152         mpfi  2.68    3.47               9.0      154.0   
3          109         mpfi  3.19    3.40              10.0      102.0   
4          136         mpfi  3.19    3.40               8.0      115.0   

   peak-rpm city-mpg  highway-mpg    price  
0    5000.0       21           27  13495.0  
1    5000.0       21           27  16500.0  
2    5000.0       19           26  16500.0  
3    5500.0       24           30  13950.0  
4    5500.0       18           22  17450.0  

[5 rows x 26 columns]

In [26]:
df.shape

(205, 26)

In [30]:
df = df.dropna()

In [31]:
df.head()

symboling  normalized-losses  make fuel-type aspiration num-of-doors  \
3           2              164.0  audi       gas        std         four   
4           2              164.0  audi       gas        std         four   
6           1              158.0  audi       gas        std         four   
8           1              158.0  audi       gas      turbo         four   
10          2              192.0   bmw       gas        std          two   

   body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
3       sedan          fwd           front        99.8  ...          109   
4       sedan          4wd           front        99.4  ...          136   
6       sedan          fwd           front       105.8  ...          136   
8       sedan          fwd           front       105.8  ...          131   
10      sedan          rwd           front       101.2  ...          108   

    fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
3          mpfi  3.19     3.4              10.0      102.0    5500.0       24   
4          mpfi  3.19     3.4               8.0      115.0    5500.0       18   
6          mpfi  3.19     3.4               8.5      110.0    5500.0       19   
8          mpfi  3.13     3.4               8.3      140.0    5500.0       17   
10         mpfi  3.50     2.8               8.8      101.0    5800.0       23   

    highway-mpg    price  
3            30  13950.0  
4            22  17450.0  
6            25  17710.0  
8            20  23875.0  
10           29  16430.0  

[5 rows x 26 columns]

In [32]:
df.shape

(159, 26)

In [39]:
df.index

Int64Index([  3,   4,   6,   8,  10,  11,  12,  13,  18,  19,
            ...
            195, 196, 197, 198, 199, 200, 201, 202, 203, 204],
           dtype='int64', length=159)

In [ ]:
['wheel-base','engine-size','horsepower']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 159 entries, 3 to 204
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0    symboling          159 non-null    int64  
 1    normalized-losses  159 non-null    float64
 2    make               159 non-null    object 
 3    fuel-type          159 non-null    object 
 4    aspiration         159 non-null    object 
 5    num-of-doors       159 non-null    object 
 6    body-style         159 non-null    object 
 7    drive-wheels       159 non-null    object 
 8    engine-location    159 non-null    object 
 9    wheel-base         159 non-null    float64
 10   length             159 non-null    float64
 11   width              159 non-null    float64
 12   height             159 non-null    float64
 13   curb-weight        159 non-null    int64  
 14   engine-type        159 non-null    object 
 15   num-of-cylinders   159 non-null    object 
 16   engine-

In [42]:
[dict(
                                    x=(1,2,3),
                                    y=(3,4,5),
                                    text="sd",
                                    mode='Scatter',

                                    name="a"
                                ) for i in range(2)]

[{'x': (1, 2, 3),
  'y': (3, 4, 5),
  'text': 'sd',
  'mode': 'Scatter',
  'name': 'a'},
 {'x': (1, 2, 3),
  'y': (3, 4, 5),
  'text': 'sd',
  'mode': 'Scatter',
  'name': 'a'}]

In [8]:
import pandas as pd

In [6]:
from datetime import datetime

In [11]:
str(datetime.now())

'2020-09-10 11:47:06.410385'

In [68]:
%%time
with open('last_fit_time.txt', 'a') as file:
    file.write(str(datetime.now())+'\n')

CPU times: user 979 µs, sys: 0 ns, total: 979 µs
Wall time: 561 µs


In [2]:
%%time
with open('fit_logs.txt', 'r') as file:
    res1 = file.readline(-1)
    print(res1)

2020-09-10 11:52:04.703404

CPU times: user 484 µs, sys: 0 ns, total: 484 µs
Wall time: 273 µs


In [4]:
%%time
with open('fit_logs.txt', 'r') as file:
    last = file.readlines()[-1]
    print(last)

2020-09-10 11:55:47.845366

CPU times: user 931 µs, sys: 150 µs, total: 1.08 ms
Wall time: 680 µs


In [42]:
pd.to_datetime(res)

Timestamp('2020-09-10 11:52:04.703404')

In [43]:
res

'2020-09-10 11:52:04.703404\n'

In [53]:
last

'2020-09-10 11:53:08.248277\n'

In [ ]:
with open(fname, 'rb') as fh:
    first = next(fh).decode()

    fh.seek(-1024, 2)
    last = fh.readlines()[-1].decode()

In [8]:
import numpy as np
import pandas as pd

In [2]:
_1 = np.array([1,2,3,4])
_2 = np.array([4,5,6,4])
_3 = np.array([7,8,9,4])

In [3]:
p = pd.DataFrame(np.vstack([_1,_2,_3]).T, columns=['predictions', 'lower', 'upper'])
p

predictions  lower  upper
0            1      4      7
1            2      5      8
2            3      6      9
3            4      4      4

In [1]:
_ = {'a':1, 'b':3}

In [6]:
list(_.keys())

['a', 'b']

In [8]:
np.concatenate([_1,np.zeros((5,), dtype=int)])

array([1, 2, 3, 4, 0, 0, 0, 0, 0])

In [4]:
np.shape(_2)

(4,)

In [ ]:
np.ones_like()

In [12]:
import numpy as np

In [13]:
np.log(1.07)/np.log(1.0005)

135.35112345347574

In [21]:
anom_df = pd.DataFrame(dtype=int)

In [22]:
pd.concat([anom_df, p['predictions']])

0
0  1.0
1  2.0
2  3.0
3  4.0

In [24]:
d = p['predictions']

In [27]:
d.iloc[-1]

4

In [36]:
pd.DataFrame([np.NaN])

0
0 NaN

In [11]:
p1 = p[['predictions', 'lower']]
p2 = p[['predictions', 'upper']].iloc[:2,:]

In [13]:
pd.merge(p1,p2, on='predictions', how='left')

predictions  lower  upper
0            1      4    7.0
1            2      5    8.0
2            3      6    NaN
3            4      4    NaN

In [14]:
p1.merge(p2)

predictions  lower  upper
0            1      4      7
1            2      5      8

In [16]:
p1.sort_values(by='lower')

predictions  lower
0            1      4
3            4      4
1            2      5
2            3      6

In [24]:
t = pd.concat([p1, p1], axis=0, ignore_index=True)['lower'].unique()

In [32]:
_ = t.sort()

In [31]:
t[::-1]

array([6, 5, 4])

In [34]:
p1.dropna(how='all', subset=['actual'])

AttributeError: module 'pandas' has no attribute 'dropna'

In [36]:
pd.datetime('2017.05.06')

/home/danil/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime instead.
  """Entry point for launching an IPython kernel.


TypeError: an integer is required (got type str)

In [1]:
from datetime import datetime

In [3]:
da

NameError: name 'da' is not defined

In [8]:
delta = timedelta(seconds = int('300S'[:-1]))
delta

In [4]:
a = pd.to_datetime(datetime.now())
a

Timestamp('2020-09-22 17:37:19.162997')

In [19]:
a+delta

Timestamp('2020-09-21 13:36:01.719063')

In [5]:
a.timestamp()

1600796239.162997

In [3]:
k = pd.read_csv('Model study/dst_ip_data_test.csv')
k

flow_key  src_ip_numeric           src_ip  \
0      9d736d3d3ce9905c0c46186254f5101a      3232266498    192.168.121.2   
1      60481cf086ea11766185490fd69dea5b      3232266498    192.168.121.2   
2      fcdbc14c12585b5c08acc606e0a15f48      3232266498    192.168.121.2   
3      53ba0e3f4d073d50e7edf8138ad4cafb      3232266498    192.168.121.2   
4      8bb9046b7995f578e09529b768375824      3232266498    192.168.121.2   
...                                 ...             ...              ...   
39426  7c4c2b8eae91da861561852b936dc05c      3232268540  192.168.128.252   
39427  9c404294609fa77d0e00133d74fa5970      3232268540  192.168.128.252   
39428  6cace9373aa898dcc050144b259a6b89      3232268540  192.168.128.252   
39429  b7dd4cfacaa51e075ae6f76cb3c78109      3232268540  192.168.128.252   
39430  3d827474a44a2c34abfd64ab7bf284c3      3232268540  192.168.128.252   

       src_port          dst_ip  dst_port  proto  pktTotalCount  \
0         49361  172.16.255.200        53     17              2   
1         52448  172.16.255.200        53     17              2   
2         53174  172.16.255.200        53     17              2   
3         55039  172.16.255.200        53     17              2   
4         55662  172.16.255.200        53     17              2   
...         ...             ...       ...    ...            ...   
39426     52813  172.16.255.200        53     17              2   
39427     62328  172.16.255.200        53     17              2   
39428     50494  172.16.255.200        53     17              2   
39429     65161  172.16.255.200        53     17              2   
39430     57053  172.16.255.200        53     17              2   

       octetTotalCount  min_ps  ...     b_flowEnd  b_flowDuration  b_min_piat  \
0                  197      71  ...  1.559764e+09             0.0         0.0   
1                  261      85  ...  1.559764e+09             0.0         0.0   
2                  172      59  ...  1.559764e+09             0.0         0.0   
3                  306      77  ...  1.559764e+09             0.0         0.0   
4                  197      71  ...  1.559764e+09             0.0         0.0   
...                ...     ...  ...           ...             ...         ...   
39426              138      61  ...  1.559770e+09             0.0         0.0   
39427              317      79  ...  1.559770e+09             0.0         0.0   
39428              268      79  ...  1.559771e+09             0.0         0.0   
39429              166      75  ...  1.559771e+09             0.0         0.0   
39430              162      73  ...  1.559771e+09             0.0         0.0   

       b_max_piat  b_avg_piat  b_std_dev_piat  flowEndReason  category  \
0             0.0         0.0             0.0              2       Web   
1             0.0         0.0             0.0              2   Network   
2             0.0         0.0             0.0              2   Network   
3             0.0         0.0             0.0              2       Web   
4             0.0         0.0             0.0              2       Web   
...           ...         ...             ...            ...       ...   
39426         0.0         0.0             0.0              2       Web   
39427         0.0         0.0             0.0              2       Web   
39428         0.0         0.0             0.0              2       Web   
39429         0.0         0.0             0.0              2       Web   
39430         0.0         0.0             0.0              2       Web   

       application_protocol     web_service  
0                       DNS       Microsoft  
1                   Unknown             DNS  
2                   Unknown             DNS  
3                       DNS       Microsoft  
4                       DNS       Microsoft  
...                     ...             ...  
39426                   DNS          Google  
39427                   DNS       Microsoft  
39428                   DNS       Mic

In [10]:
pd.to_datetime('2020/09/21 13:36:01')

Timestamp('2020-09-21 13:36:01')

In [12]:
c1 = k['src_port'] > 49361
c1

0        False
1         True
2         True
3         True
4         True
         ...  
39426     True
39427     True
39428     True
39429     True
39430     True
Name: src_port, Length: 39431, dtype: bool

In [16]:
c2 = k['src_port'] < 49500
c2

0         True
1        False
2        False
3        False
4        False
         ...  
39426    False
39427    False
39428    False
39429    False
39430    False
Name: src_port, Length: 39431, dtype: bool

In [18]:
(c1 & c2).unique()

array([False,  True])

In [23]:
t = pd.DataFrame(columns=['1','2'])
t

Empty DataFrame
Columns: [1, 2]
Index: []

In [37]:
pd.concat([t, pd.DataFrame([0, 0, 0])], axis=0)

1    2    0
0  NaN  NaN  0.0
1  NaN  NaN  0.0
2  NaN  NaN  0.0

In [46]:
#a = np.zeros(shape=(1,2), dtype=int)
df = pd.DataFrame(np.NaN,columns=['col1','col2'], index=[0])

In [47]:
df

col1  col2
0   NaN   NaN

In [23]:
empty_df = k[k['dst_port'] == 100]
empty_df

Empty DataFrame
Columns: [flow_key, src_ip_numeric, src_ip, src_port, dst_ip, dst_port, proto, pktTotalCount, octetTotalCount, min_ps, max_ps, avg_ps, std_dev_ps, flowStart, flowEnd, flowDuration, min_piat, max_piat, avg_piat, std_dev_piat, f_pktTotalCount, f_octetTotalCount, f_min_ps, f_max_ps, f_avg_ps, f_std_dev_ps, f_flowStart, f_flowEnd, f_flowDuration, f_min_piat, f_max_piat, f_avg_piat, f_std_dev_piat, b_pktTotalCount, b_octetTotalCount, b_min_ps, b_max_ps, b_avg_ps, b_std_dev_ps, b_flowStart, b_flowEnd, b_flowDuration, b_min_piat, b_max_piat, b_avg_piat, b_std_dev_piat, flowEndReason, category, application_protocol, web_service]
Index: []

[0 rows x 50 columns]

In [21]:
len(empty_df)

0

In [17]:
null_df = pd.DataFrame(np.NaN, columns=empty_df.columns, index=[0])
null_df.loc[0, 'flowStart'] = pd.to_datetime(datetime.now())
null_df

flow_key  src_ip_numeric  src_ip  src_port  dst_ip  dst_port  proto  \
0       NaN             NaN     NaN       NaN     NaN       NaN    NaN   

   pktTotalCount  octetTotalCount  min_ps  ...  b_flowEnd  b_flowDuration  \
0            NaN              NaN     NaN  ...        NaN             NaN   

   b_min_piat b_max_piat  b_avg_piat  b_std_dev_piat  flowEndReason  category  \
0         NaN        NaN         NaN             NaN            NaN       NaN   

   application_protocol  web_service  
0                   NaN          NaN  

[1 rows x 50 columns]

In [16]:
pd.to_datetime(datetime.now())

Timestamp('2020-09-23 12:52:03.854103')

In [19]:
null_df.resample('300S', on='flowStart').sum()

flow_key  src_ip_numeric  src_ip  src_port  dst_ip  \
flowStart                                                                 
2020-09-23 12:50:00       0.0             0.0     0.0       0.0     0.0   

                     dst_port  proto  pktTotalCount  octetTotalCount  min_ps  \
flowStart                                                                      
2020-09-23 12:50:00       0.0    0.0            0.0              0.0     0.0   

                     ...  b_flowEnd  b_flowDuration  b_min_piat  b_max_piat  \
flowStart            ...                                                      
2020-09-23 12:50:00  ...        0.0             0.0         0.0         0.0   

                     b_avg_piat  b_std_dev_piat  flowEndReason  category  \
flowStart                                                                  
2020-09-23 12:50:00         0.0             0.0            0.0       0.0   

                     application_protocol  web_service  
flowStart                                               
2020-09-23 12:50:00                   0.0          0.0  

[1 rows x 49 columns]

# Tasks sheduler

In [4]:
import schedule
import time
import pandas as pd
from datetime import timedelta

In [5]:
def job():
    print("I'm working... " + str(pd.to_datetime('now') + timedelta(hours=3)))

In [6]:
job()

I'm working... 2020-09-23 15:24:13.387083


In [7]:
schedule.every(2).minutes.at(":30").do(job)


while True:
    schedule.run_pending()
    time.sleep(1)

I'm working... 2020-09-23 15:25:30.648375
I'm working... 2020-09-23 15:27:30.790435
I'm working... 2020-09-23 15:29:30.927499
I'm working... 2020-09-23 15:31:30.067335
I'm working... 2020-09-23 15:33:30.206688
I'm working... 2020-09-23 15:35:30.341549
I'm working... 2020-09-23 15:37:30.484029
I'm working... 2020-09-23 15:39:30.621381
I'm working... 2020-09-23 15:41:30.759183
I'm working... 2020-09-23 15:43:30.889229
I'm working... 2020-09-23 15:45:30.026952


KeyboardInterrupt: 

# Dict sending

In [2]:
d = {'temp':1, 'co':2}

In [3]:
j = json.dumps(d)
j

'{"temp": 1, "co": 2}'

In [4]:
json.loads(j)

{'temp': 1, 'co': 2}

In [7]:
a = pd.DataFrame([d])
a

temp  co
0     1   2

In [8]:
dict(zip(a.columns, a.iloc[0]))

{'temp': 1, 'co': 2}

## Make clust data dashboard

In [2]:
lag = np.array([1,2,3,4,5])
cur = np.array([11,12,13,14,15])

In [5]:
lag, cur

(array([1, 2, 3, 4, 5]), array([11, 12, 13, 14, 15]))

In [11]:
np.vstack([lag,  cur]).transpose(1,0)

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15]])